---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: app
        image: quay.io/gauravkumar9130/ecart-microservices:frontend
        imagePullPolicy: Always
        env:
        - name: MYSQL_DB_HOST
          value: db
        - name: MYSQL_DB_PASSWORD
          value: test
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: frontend

