apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
 name: ecart-ingress
 annotations:
   kubernetes.io/ingress.class: nginx
spec:
 rules:
 - http:
    paths:
    - path: /
      pathType: Exact
      backend:
       service:
        name: frontend
        port:
         number: 5000
    - path: /catalogue
      pathType: Exact
      backend:
       service:
        name: catalogue
        port:
         number: 5001
    - path: /user
      pathType: Exact
      backend:
       service:
        name: user
        port:
         number: 5002
    - path: /cart
      pathType: Exact
      backend:
       service:
        name: cart
        port:
         number: 5003
    - path: /orders
      pathType: Exact
      backend:
       service:
        name: orders
        port:
         number: 5004
    - path: /payment
      pathType: Exact
      backend:
       service:
        name: payment
        port:
         number: 5005
